get-persistence:
  service:
    version: 1.0.0
nacos:
  host: 192.168.42.7
  port: 8848
  username: nacos
  password: nacos

spring:
  application:
    name: domain-persistence-get-persistence-service
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/domaintransfer?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
dubbo:
  registry:
    address: nacos://${nacos.host}:${nacos.port}/?username=${nacos.username}&password=${nacos.password}
  scan:
    base-packages: com.demo.domain.persistence.get.persistence.service
  protocol:
    name: dubbo
    port: -1
  #均衡策略
  provider:
    loadbalance: roundrobin